### ISSUE TITLE
Multiple errors when setting up the hovercraft

### ISSUE THREAD

**Issue by GustavoJCL** [patrickpichler/hovercraft.nvim#2]
Hi, I configured hovercraft following the examples of the repository, but when i try to use any of this functions i have similar errors, this is my config:
```
{
    "patrickpichler/hovercraft.nvim",
    lazy = true,
    event = "BufRead",
    dependencies = {
      { "nvim-lua/plenary.nvim" },
    },
    opts = function()
      local opts = {}
      -- local hc = require "hovercraft"
      local wk = require "which-key"
      opts.providers = {
        providers = {
          {
            "LSP",
            require("hovercraft.provider.lsp.hover").new(),
          },
          {
            "Man",
            require("hovercraft.provider.man").new(),
          },
          {
            "Dictionary",
            require("hovercraft.provider.dictionary").new(),
          },
        },
      }
      opts.window = {
        border = "single",
      }
      -- opts.keys = {}

      wk.register {
        ["<C-p>"] = { function() require("hovercraft").scroll { delta = -4 } end, "Scroll up" },
        ["<C-i>"] = { function() require("hovercraft").scroll { delta = 4 } end, "Scroll down" },
        ["<TAB>"] = { function() require("hovercraft").hover_next() end, "Next hover" },
        ["<S-TAB>"] = {
          function() require("hovercraft").hover_next { step = -1 } end,
          "Previous hover",
        },
      }

      return opts
    end,
  },
```
i have this error whit every function:

```
E5108: Error executing lua: ...local/share/nvim/lazy/hovercraft.nvim/lua/hovercraft.lua:32: attempt to call field 'unpa
ck' (a nil value)
stack traceback:
        ...local/share/nvim/lazy/hovercraft.nvim/lua/hovercraft.lua:32: in function 'hover_next'
        /home/gus/.config/nvim/lua/plugins/hovercraft.lua:38: in function </home/gus/.config/nvim/lua/plugins/hovercraf
t.lua:38>
```
![image](https://github.com/patrickpichler/hovercraft.nvim/assets/93671143/e89c16c2-b0c1-462f-9f94-b0dc0a5cc881)

**Comment by patrickpichler** [comment]
Thanks for opening an issue! 

I just noticed the example in the docs is currently not containing a way on how to trigger hovercraft! 

How exactly did you trigger the functions though? There might be another issues as well :) 

I adapted the sample to contain a trigger on `K` and it works for me:
```lua
{
    "patrickpichler/hovercraft.nvim",
    lazy = true,
    event = "BufRead",
    dependencies = {
      { "nvim-lua/plenary.nvim" },
    },
    opts = function()
      local opts = {}
      -- local hc = require "hovercraft"
      local wk = require "which-key"
      opts.providers = {
        providers = {
          {
            "LSP",
            require("hovercraft.provider.lsp.hover").new(),
          },
          {
            "Man",
            require("hovercraft.provider.man").new(),
          },
          {
            "Dictionary",
            require("hovercraft.provider.dictionary").new(),
          },
        },
      }
      opts.window = {
        border = "single",
      }
      -- opts.keys = {}

      wk.register {
        ["<C-p>"] = { function() require("hovercraft").scroll { delta = -4 } end, "Scroll up" },
        ["<C-i>"] = { function() require("hovercraft").scroll { delta = 4 } end, "Scroll down" },
        ["<TAB>"] = { function() require("hovercraft").hover_next() end, "Next hover" },
        ["<S-TAB>"] = {
          function() require("hovercraft").hover_next { step = -1 } end,
          "Previous hover",
        },
      }

      return opts
    end,
    keys = {
      { "K", function()
        local hovercraft = require("hovercraft")

        if hovercraft.is_visible() then
          hovercraft.enter_popup()
        else
          hovercraft.hover()
        end
      end },
    },
  }
```

Could you give it a shot and report back? Also which version os nvim are you using?

**Comment by GustavoJCL** [comment]
thanks, it work with the letter K, but the other functions <C-p>, <C-i>, <TAB>, <S-TAB> didn't work

![image](https://github.com/patrickpichler/hovercraft.nvim/assets/93671143/2290ca07-19f4-491d-ad2f-770580cf08b1)
![image](https://github.com/patrickpichler/hovercraft.nvim/assets/93671143/2843976d-0977-4221-afd3-e6829d484958)
![image](https://github.com/patrickpichler/hovercraft.nvim/assets/93671143/6ac84c60-8991-4adc-8770-cc01e9bbbe98)

I'm using Arch Linux and my neovim version is `0.9.5`

**Comment by GustavoJCL** [comment]
yes, i have a similar error pressing `K` and then `<TAB>`
![image](https://github.com/patrickpichler/hovercraft.nvim/assets/93671143/e6412b11-e7b4-404e-a84b-5bff2e949c35)

**Comment by GustavoJCL** [comment]
i don't know if is necessary add `hovercraft` as a dependency, i use `which-key` on another plugin `ferris.nvim` and i didn't need to add it as a dependency

**Comment by GustavoJCL** [comment]
i works fine, the problem is for the other functions
![image](https://github.com/patrickpichler/hovercraft.nvim/assets/93671143/05d3f27c-175e-4ff8-befa-c7e0e48b55aa)

**Comment by GustavoJCL** [comment]
no, the error doesn't appear but when I press <TAB> and another key it just didn't do anything

**Comment by patrickpichler** [comment]
With the config i pasted above, nothing happens if you press `K` and then `<TAB>`?

**Comment by GustavoJCL** [comment]
yes, now i have this error:
```
E5108: Error executing lua: ...local/share/nvim/lazy/hovercraft.nvim/lua/hovercraft.lua:32: attempt to call field 'unpa
ck' (a nil value)
stack traceback:
        ...local/share/nvim/lazy/hovercraft.nvim/lua/hovercraft.lua:32: in function 'is_visible'
        /home/gus/.config/nvim/lua/plugins/hovercraft.lua:15: in function </home/gus/.config/nvim/lua/plugins/hovercraf
t.lua:12>
```

![image](https://github.com/patrickpichler/hovercraft.nvim/assets/93671143/8f16dbf7-8ae5-484b-a80b-6609e38fd95e)

**Comment by patrickpichler** [comment]
Interesting! It seems like `table.unpack` was added with lua 5.4 and nvim stays at lua 5.1. I do not understand though why it is working for me though, so it might be that the brew version of nvim is bundled with a newer lua release? 

Anyway there should also be an `unpack` function, that should be identical to `table.unpack`. I will try to adapt the code and let you know :)

**Comment by patrickpichler** [comment]
Ok, could you please try updating to the latest version and test it again?

**Comment by GustavoJCL** [comment]
thanks, now everything works fine, including with `which-key`, I think maybe you compiled neovim with lua 5.4, i found the default version of lua for neovim is [5.1](https://neovim.io/doc/user/lua.html)

**Comment by patrickpichler** [comment]
Awesome! I will close the issue then :)
