### ISSUE TITLE
Key bindings override active buffer keymaps

### ISSUE THREAD

**Issue by hadynz** [patrickpichler/hovercraft.nvim#5]
Bug: Keybindings are NOT scoped to the "hover buffer" and override the keymaps of the current "active buffer".

For example:

```javascript
keys = {
  { '<C-u>',   function() require('hovercraft').scroll({ delta = -4 }) end },
  { '<C-d>',   function() require('hovercraft').scroll({ delta = 4 }) end },
}
```

On opening an active buffer, `<C-u>` and `<C-d>` will page up and page down respectively by default.

Once I toggle hovercraft hover, `<C-u>` and `<C-d>` are overridden without any constraints (i.e. for both "hover buffer" and "active buffer"). The bindings in the hover buffer work as expected. However, once the hovercraft hover is closed, the keymaps are not reset and default behaviour stops working.

The only work around is to "reset" - by closing the current active buffer and opening again.

**Comment by patrickpichler** [comment]
Hey @hadynz!

Thanks for the report! Could you by any chance share your neovim config, so that I can try reproducing the issue? 
Also which version of neovim are you using?

**Comment by patrickpichler** [comment]
Ah, I think I managed to reproduce the issue locally. I will try to fix it ASAP :)

**Comment by patrickpichler** [comment]
@hadynz I have pushed a fix, could you update your config and try again? Feel free to reopen the issue, if the problem still persists :)
